name: beauty_solution_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  # ****** Localization *******
  flutter_localizations:
    sdk: flutter
  


  # ****** UI *******
  cupertino_icons: ^1.0.8  # for cupertino icons
  
  flutter_screenutil: ^5.9.0  # for responsive ui
  syncfusion_flutter_charts: ^26.1.40
  flutter_svg: ^2.0.10+1

  # ****** Images *******

  cached_network_image: ^3.3.1 # for caching images from network
  any_link_preview: ^3.0.2
  #image_picker: ^0.8.4+4


  # ****** Network *******
#  dio: ^5.4.3    # for network requests and api calls
  url_launcher: ^6.3.0  # for launching urls in browser or other apps
  url_launcher_web: ^2.3.1
 # http_parser: ^4.0.2 # for parsing http requests
  #http: ^1.2.1

  # ! Services


  # ****** Share Plus *******
  share_plus: ^9.0.0
  get: ^4.6.6


  # ****** Printing *******
  printing: ^5.9.0
  pdf: ^3.11.0
  google_fonts: ^4.0.3 



  beamer: ^1.6.1






    # *****general*******
 # permission_handler: ^10.4.5  # for permission handling in app
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
#  build_runner: ^2.4.8
 # freezed: ^2.5.2

flutter:

  uses-material-design: true

  # *To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/jsons/
    - assets/gifs/
    - assets/jsons/lang/
 #*To add fonts to your application, add a fonts section, like this:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MonsieurLaDoulaise-Regular.ttf
          weight: 500
        - asset: assets/fonts/MonsieurLaDoulaise-Regular.ttf
          weight: 200
