name: beauty_station_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  # ****** Localization *******
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # for localization in app 


  # ****** UI *******
  cupertino_icons: ^1.0.8  # for cupertino icons
  flutter_spinkit: ^5.2.1  # for loading spinners in app
  flutter_screenutil: ^5.9.0  # for responsive ui
  device_preview: ^1.1.0  # for preview app in different devices
  figma_squircle: ^0.5.3 # for squircle shape in app ui
  dotted_border: ^2.1.0 # for dotted border in app
  flutter_keyboard_visibility: ^6.0.0 # for check keyboard is open or not
  pin_code_fields: ^8.0.1 # for otp text field ui in app
  flutter_cupertino_date_picker_fork: ^1.0.7 # for date picker in app 
  flutter_rating_bar: ^4.0.1 # for rating bar in app
  shimmer: ^3.0.0 # for shimmer effect in app
  syncfusion_flutter_charts: ^26.1.40
  any_link_preview: ^3.0.2

  # ****** Images *******
  flutter_svg: ^2.0.10  # for svg images in app
  cached_network_image: ^3.3.1 # for caching images from network
  #image_picker: ^0.8.4+4

  # ****** animations *******
  flutter_animate: ^4.5.0 # for animations in app
  lottie: ^3.1.2  # for lottie animations in app
  # ****** Network *******
  dio: ^5.4.3    # for network requests and api calls
  url_launcher: ^6.3.0  # for launching urls in browser or other apps
  http_parser: ^4.0.2 # for parsing http requests

  # ****** caching *******
  hive_flutter: ^1.1.0 # for caching data in cache storage

  # ! Services

  # ****** State Management *******
  flutter_bloc: ^8.1.5  # for State Management
  freezed_annotation: ^2.4.1 # for generating imitable freezed classes and methods 
  get_it: ^7.7.0 # for dependency injection

  # ****** Share Plus *******
  share_plus: ^9.0.0
  get: ^4.6.6


  go_router: ^13.2.4
  beamer: ^1.6.1

  # ****** DataBase And Files *******
  path_provider: ^2.1.3
  file_picker: ^8.0.3 # for file picker for images and files


  #********firebase*************
  firebase_core: ^2.32.0
  fcm_config: ^3.5.3 


    # *****general*******
  permission_handler: ^11.3.1  # for permission handling in app
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2

flutter:

  uses-material-design: true

  # *To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/jsons/
    - assets/gifs/
    - assets/jsons/lang/
    - assets/jsons/lottifiles/
 #*To add fonts to your application, add a fonts section, like this:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
